In [2]:
#Example1 : Obtained Marks Calculation

pct_marks = [75,55,65,80,95]
tot_marks = 500
type(pct_marks)

list

In [3]:
obt_marks = (pct_marks * tot_marks)/100

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [5]:
import numpy as np

pct_marks = [75,55,65,80,95]
tot_marks = 500

pct_arr = np.array(pct_marks)                       #np.array([])
tot_arr = np.array(tot_marks)

In [6]:
obt_arr = (pct_arr * tot_arr)/100
print(obt_arr)

[375. 275. 325. 400. 475.]


In [7]:
#BMI CALCULATION:

weight = [65,56,76,45,66]
height = [1.5,1.2,1.9,1.0,1.5]

In [8]:
bmi = weight/(height**2)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [10]:
import numpy as np

weight_arr = np.array([65,56,76,45,66])
height_arr = np.array([1.5,1.2,1.9,1.0,1.5])

In [11]:
bmi_np = np.round(weight_arr/(height_arr**2),2)
print(bmi_np)

[28.89 38.89 21.05 45.   29.33]


In [12]:
#Creating first Numpy Array???

my_arr = np.array([[1,2,3,4], [5,6,7,8]])
print(my_arr)

[[1 2 3 4]
 [5 6 7 8]]


In [15]:
my_arr1d = np.array([1,2,3,4])                           #1dimension
type(my_arr1d)

numpy.ndarray

In [19]:
my_arr2 = np.array([[1.5,1.2,1.6],['A  ','B  ','C  ']])
print(my_arr2.dtype)
#my_arr2[1][2]

<U32


In [21]:
my_arr2 = np.array([['A','B','C'],['D','E','F']])
my_arr2

array([['A', 'B', 'C'],
       ['D', 'E', 'F']], dtype='<U1')

In [23]:
#Creating Empty Numpy Array???

empt_arr = np.array([])
print(empt_arr)

[]


In [26]:
# Create a full array
np.full((2,2),1)

array([[1, 1],
       [1, 1]])

In [29]:
# Create a ones array
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
# Create a zeros array
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [32]:
# Create an array of evenly-spaced values
np.arange(10,45,5)

array([10, 15, 20, 25, 30, 35, 40])

In [37]:
# Create an array of evenly-spaced values
np.linspace(0,12,3)

array([ 0.,  6., 12.])

In [38]:
#Create Identity Matrix

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
#Load Data Set using Numpy:

x,y,z = np.loadtxt('C:\\Users\\rahul3.tiwari\\Desktop\\Data.txt',skiprows = 1,unpack = True)
print(type(x))
print(z)

<class 'numpy.ndarray'>
[3. 6. 9.]


In [42]:
#Saving the Data Set if any in NUMPY:

import numpy as np

my_dat = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])

np.savetxt('C:\\Users\\rahul3.tiwari\\Desktop\\test.txt', my_dat, delimiter=',')

In [48]:
#Mathematical Operation with Numpy:

x =np.array([2,4,4,8])

y = np.array([8,8,7,8])

print('Addition:')
print(np.add(x,y))

print('Substraction:')
print(np.subtract(x,y))

print('Multiplication')
print(np.multiply(x,y))

print('Division')
print(np.divide(y,x))

print('Remainder')
print(np.remainder(y,x))

Addition:
[10 12 11 16]
Substraction:
[-6 -4 -3  0]
Multiplication
[16 32 28 64]
Division
[4.   2.   1.75 1.  ]
Remainder
[0 0 3 0]


In [51]:
#SLICING in NUMPY similar to Lists???

x =np.array([2,4,4,8])
print(x)

x[1:3], x[0:2]

[2 4 4 8]


(array([4, 4]), array([2, 4]))

In [56]:
#INDEXING in NUMPY????

y = np.array([[8,9,10,11],[4,5,6,7]])
print(y)

y[0][2]

[[ 8  9 10 11]
 [ 4  5  6  7]]


10

In [57]:
#BROADCASTING in NUMPY????

x =np.array([2,4,4,8])
y = np.array([[8,8,8,8],[4,8,8,4]])


print(np.add(x,y))

print(np.subtract(y,x))

print(np.multiply(x,y))

print(np.divide(y,x))

print(np.remainder(y,x))

[[10 12 12 16]
 [ 6 12 12 12]]
[[ 6  4  4  0]
 [ 2  4  4 -4]]
[[16 32 32 64]
 [ 8 32 32 32]]
[[4.  2.  2.  1. ]
 [2.  2.  2.  0.5]]
[[0 0 0 0]
 [0 0 0 4]]


In [59]:
#BOOLEAN INDEXING in NUMPY????

x =np.array([2,4,4,8])
y = np.array([[8,8,3,2],[4,8,8,4]])

z = y[y > 4]
print(z)
type(z)

[8 8 8 8]


numpy.ndarray

In [61]:
#Modification/Alteration in NUMPY Arrays???

x = np.array([2,4,4,8])
x = np.append(x,[3,4,5,7,6])
print(x)
x = np.insert(x,1,9)
print(x)
x = np.delete(x,7)
print(x)

[2 4 4 8 3 4 5 7 6]
[2 9 4 4 8 3 4 5 7 6]
[2 9 4 4 8 3 4 7 6]


In [142]:
#Statistical Operations with Numpy Arrays???

std_marks = np.array([65,75,75,78,78,79,78,85,86,95])
mean_std = np.mean(std_marks)
print(mean_std)

median_std = np.median(std_marks)
print('Median is : '+str(median_std))

stdd = np.std(std_marks)
print('Standard Deviation is : '+str(stdd))

var = np.var(std_marks)
print('Variance is : '+str(var))

pct25 = np.percentile(std_marks,25,axis = 0)
print(pct25)

79.4
Median is : 78.0
Standard Deviation is : 7.552483035399682
Variance is : 57.04
75.75


In [62]:
#Iterating over Numpy Array???

x = np.arange(0,50,10)
print(x)


for i in np.nditer(x):
    print (i)

[ 0 10 20 30 40]
0
10
20
30
40
